### ISSUE TITLE
Barcelona Logistics

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/pm-projects#31]
- [x] Identify & book venue location #63 
- [x] Identify & book hotel for localizers #64
- [x] Book travel for localizers #65
- [ ] Find & book restaurants or catering for 2 lunches & 3 dinners. #66
- [x] Identify visa needs. #67
- [ ] Identify transportation needs and make necessary arrangements.  #68
- [ ] Get name tags and gear for localizers. #70
- [x] Identify possible cultural activities. #69
- [ ] Create Telegram group. #71
